name: Build and deploy multi-solution app to Azure Web App - AppTest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-AplicacionCliente:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build AplicacionCliente
        run: dotnet build AplicacionCliente.API/AplicacionCliente.API.sln --configuration Release

      - name: Publish AplicacionCliente
        run: dotnet publish AplicacionCliente.API/AplicacionCliente.API.sln -c Release -o ${{env.DOTNET_ROOT}}/AplicacionCliente

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: AplicacionCliente
          path: ${{env.DOTNET_ROOT}}/AplicacionCliente

  build-AplicacionProductos:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Build AplicacionProductos
        run: dotnet build AplicacionProducto.API/AplicacionProducto.API.sln --configuration Release

      - name: Publish AplicacionProductos
        run: dotnet publish AplicacionProducto.API/AplicacionProducto.API.sln -c Release -o ${{env.DOTNET_ROOT}}/AplicacionProductos

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: AplicacionProductos
          path: ${{env.DOTNET_ROOT}}/AplicacionProductos

  build-AplicacionBodega:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Build AplicacionBodega
        run: dotnet build AplicacionBodega.API/AplicacionBodega.API.sln --configuration Release

      - name: Publish AplicacionBodega
        run: dotnet publish AplicacionBodega.API/AplicacionBodega.API.sln -c Release -o ${{env.DOTNET_ROOT}}/AplicacionBodega

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: AplicacionBodega
          path: ${{env.DOTNET_ROOT}}/AplicacionBodega

  build-static:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Archive static files
        run: zip -r my-static-site.zip front/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: my-static-site.zip

  deploy:
    runs-on: ubuntu-latest
    needs: [build-AplicacionCliente, build-AplicacionProductos, build-AplicacionBodega, build-static]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download AplicacionCliente artifact
        uses: actions/download-artifact@v4
        with:
          name: AplicacionCliente

      - name: Download AplicacionProductos artifact
        uses: actions/download-artifact@v4
        with:
          name: AplicacionProductos

      - name: Download AplicacionBodega artifact
        uses: actions/download-artifact@v4
        with:
          name: AplicacionBodega

      - name: Download static-site artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0DD612ADF47847D18DD42C643E6B45A9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5016CCEA95EB4DFBAD81CD0C129F273D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_86736B8430B541249C68635FC0945833 }}

      - name: Deploy AplicacionCliente to Azure Web App
        id: deploy-to-webapp-AplicacionCliente
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AppTestAplicacionCliente'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/AplicacionCliente

      - name: Deploy AplicacionProductos to Azure Web App
        id: deploy-to-webapp-AplicacionProductos
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AppTestAplicacionProductos'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/AplicacionProductos

      - name: Deploy AplicacionBodega to Azure Web App
        id: deploy-to-webapp-AplicacionBodega
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AppTestAplicacionBodega'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/AplicacionBodega

      - name: Deploy static site to Azure Web App
        id: deploy-to-webapp-static
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AppTestStatic'
          slot-name: 'Production'
          package: my-static-site.zip
