name: Build and deploy static site to Azure Web App - AppTestStatic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-static:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Archive static files
        run: zip -r my-static-site.zip front/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: my-static-site.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-static
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download static-site artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_49F32262380D4BD6859ABB56FA95CFDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_26136384CC8347159FAC75FCA239C640 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_516D3E6714DB4071A14CCF898E05F408 }}

      - name: Deploy static site to Azure Web App
        id: deploy-to-webapp-static
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AppTestStatic'
          slot-name: 'Production'
          package: static-site/my-static-site.zip
